//
// Copyright (c) 2016 Advanced Micro Devices, Inc. All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//

#pragma once

#include "Shaders\inc\CS_DEINTERLEAVE_X1_MSAA_X1_DEPTH.inc"
#include "Shaders\inc\CS_DEINTERLEAVE_X1_MSAA_X1_DEPTH_NORMAL.inc"
#include "Shaders\inc\CS_DEINTERLEAVE_X2_MSAA_X1_DEPTH.inc"
#include "Shaders\inc\CS_DEINTERLEAVE_X2_MSAA_X1_DEPTH_NORMAL.inc"
#include "Shaders\inc\CS_DEINTERLEAVE_X4_MSAA_X1_DEPTH.inc"
#include "Shaders\inc\CS_DEINTERLEAVE_X4_MSAA_X1_DEPTH_NORMAL.inc"
#include "Shaders\inc\CS_DEINTERLEAVE_X8_MSAA_X1_DEPTH.inc"
#include "Shaders\inc\CS_DEINTERLEAVE_X8_MSAA_X1_DEPTH_NORMAL.inc"

const BYTE * CS_AO_DEINTERLEAVE_Data[] =
{
  CS_DEINTERLEAVE_X1_MSAA_X1_DEPTH_Data,
  CS_DEINTERLEAVE_X1_MSAA_X1_DEPTH_NORMAL_Data,

  CS_DEINTERLEAVE_X2_MSAA_X1_DEPTH_Data,
  CS_DEINTERLEAVE_X2_MSAA_X1_DEPTH_NORMAL_Data,

  CS_DEINTERLEAVE_X4_MSAA_X1_DEPTH_Data,
  CS_DEINTERLEAVE_X4_MSAA_X1_DEPTH_NORMAL_Data,

  CS_DEINTERLEAVE_X8_MSAA_X1_DEPTH_Data,
  CS_DEINTERLEAVE_X8_MSAA_X1_DEPTH_NORMAL_Data,
};

int          CS_AO_DEINTERLEAVE_Size[] =
{
  sizeof(CS_DEINTERLEAVE_X1_MSAA_X1_DEPTH_Data),
  sizeof(CS_DEINTERLEAVE_X1_MSAA_X1_DEPTH_NORMAL_Data),

  sizeof(CS_DEINTERLEAVE_X2_MSAA_X1_DEPTH_Data),
  sizeof(CS_DEINTERLEAVE_X2_MSAA_X1_DEPTH_NORMAL_Data),

  sizeof(CS_DEINTERLEAVE_X4_MSAA_X1_DEPTH_Data),
  sizeof(CS_DEINTERLEAVE_X4_MSAA_X1_DEPTH_NORMAL_Data),

  sizeof(CS_DEINTERLEAVE_X8_MSAA_X1_DEPTH_Data),
  sizeof(CS_DEINTERLEAVE_X8_MSAA_X1_DEPTH_NORMAL_Data),
};


#include "Shaders\inc\PS_DEINTERLEAVE_X1_MSAA_X1_DEPTH.inc"
#include "Shaders\inc\PS_DEINTERLEAVE_X1_MSAA_X1_DEPTH_NORMAL.inc"
#include "Shaders\inc\PS_DEINTERLEAVE_X2_MSAA_X1_DEPTH.inc"
#include "Shaders\inc\PS_DEINTERLEAVE_X2_MSAA_X1_DEPTH_NORMAL.inc"
#include "Shaders\inc\PS_DEINTERLEAVE_X4_MSAA_X1_DEPTH.inc"
#include "Shaders\inc\PS_DEINTERLEAVE_X4_MSAA_X1_DEPTH_NORMAL.inc"
#include "Shaders\inc\PS_DEINTERLEAVE_X8_MSAA_X1_DEPTH.inc"
#include "Shaders\inc\PS_DEINTERLEAVE_X8_MSAA_X1_DEPTH_NORMAL.inc"

const BYTE * PS_AO_DEINTERLEAVE_Data[] =
{
  PS_DEINTERLEAVE_X1_MSAA_X1_DEPTH_Data,
  PS_DEINTERLEAVE_X1_MSAA_X1_DEPTH_NORMAL_Data,

  PS_DEINTERLEAVE_X2_MSAA_X1_DEPTH_Data,
  PS_DEINTERLEAVE_X2_MSAA_X1_DEPTH_NORMAL_Data,

  PS_DEINTERLEAVE_X4_MSAA_X1_DEPTH_Data,
  PS_DEINTERLEAVE_X4_MSAA_X1_DEPTH_NORMAL_Data,

  PS_DEINTERLEAVE_X8_MSAA_X1_DEPTH_Data,
  PS_DEINTERLEAVE_X8_MSAA_X1_DEPTH_NORMAL_Data,
};

int          PS_AO_DEINTERLEAVE_Size[] =
{
  sizeof(PS_DEINTERLEAVE_X1_MSAA_X1_DEPTH_Data),
  sizeof(PS_DEINTERLEAVE_X1_MSAA_X1_DEPTH_NORMAL_Data),

  sizeof(PS_DEINTERLEAVE_X2_MSAA_X1_DEPTH_Data),
  sizeof(PS_DEINTERLEAVE_X2_MSAA_X1_DEPTH_NORMAL_Data),

  sizeof(PS_DEINTERLEAVE_X4_MSAA_X1_DEPTH_Data),
  sizeof(PS_DEINTERLEAVE_X4_MSAA_X1_DEPTH_NORMAL_Data),

  sizeof(PS_DEINTERLEAVE_X8_MSAA_X1_DEPTH_Data),
  sizeof(PS_DEINTERLEAVE_X8_MSAA_X1_DEPTH_NORMAL_Data),
};

#include "Shaders\inc\VS_FULLSCREEN.inc"

#include "Shaders\inc\PS_UPSAMPLE.inc"

#include "Shaders\inc\PS_DILATE_YNN.inc"
#include "Shaders\inc\PS_DILATE_NYN.inc"
#include "Shaders\inc\PS_DILATE_NNY.inc"
#include "Shaders\inc\PS_DILATE_YYN.inc"
#include "Shaders\inc\PS_DILATE_YNY.inc"
#include "Shaders\inc\PS_DILATE_NYY.inc"
#include "Shaders\inc\PS_DILATE_YYY.inc"

const BYTE * PS_AO_DILATE_Data[] =
{
  NULL,
  PS_DILATE_YNN_Data,
  PS_DILATE_NYN_Data,
  PS_DILATE_YYN_Data,
  PS_DILATE_NNY_Data,
  PS_DILATE_YNY_Data,
  PS_DILATE_NYY_Data,
  PS_DILATE_YYY_Data,
};

int          PS_AO_DILATE_Size[] =
{
  0,
  sizeof(PS_DILATE_YNN_Data),
  sizeof(PS_DILATE_NYN_Data),
  sizeof(PS_DILATE_YYN_Data),
  sizeof(PS_DILATE_NNY_Data),
  sizeof(PS_DILATE_YNY_Data),
  sizeof(PS_DILATE_NYY_Data),
  sizeof(PS_DILATE_YYY_Data),
};

#include "Shaders\inc\PS_OUTPUT.inc"

#include "Shaders\inc\CS_FILTER_X_RADIUS_2.inc"
#include "Shaders\inc\CS_FILTER_Y_RADIUS_2.inc"
#include "Shaders\inc\CS_FILTER_X_RADIUS_4.inc"
#include "Shaders\inc\CS_FILTER_Y_RADIUS_4.inc"
#include "Shaders\inc\CS_FILTER_X_RADIUS_8.inc"
#include "Shaders\inc\CS_FILTER_Y_RADIUS_8.inc"
#include "Shaders\inc\CS_FILTER_X_RADIUS_16.inc"
#include "Shaders\inc\CS_FILTER_Y_RADIUS_16.inc"
#include "Shaders\inc\CS_FILTER_X_RADIUS_32.inc"
#include "Shaders\inc\CS_FILTER_Y_RADIUS_32.inc"

const BYTE * CS_AMD_BLUR_Data[] =
{
  CS_FILTER_X_RADIUS_2_Data,
  CS_FILTER_Y_RADIUS_2_Data,
  CS_FILTER_X_RADIUS_4_Data,
  CS_FILTER_Y_RADIUS_4_Data,
  CS_FILTER_X_RADIUS_8_Data,
  CS_FILTER_Y_RADIUS_8_Data,
  CS_FILTER_X_RADIUS_16_Data,
  CS_FILTER_Y_RADIUS_16_Data,
  CS_FILTER_X_RADIUS_32_Data,
  CS_FILTER_Y_RADIUS_32_Data,
};

int          CS_AMD_BLUR_Size[] =
{
  sizeof(CS_FILTER_X_RADIUS_2_Data),
  sizeof(CS_FILTER_Y_RADIUS_2_Data),
  sizeof(CS_FILTER_X_RADIUS_4_Data),
  sizeof(CS_FILTER_Y_RADIUS_4_Data),
  sizeof(CS_FILTER_X_RADIUS_8_Data),
  sizeof(CS_FILTER_Y_RADIUS_8_Data),
  sizeof(CS_FILTER_X_RADIUS_16_Data),
  sizeof(CS_FILTER_Y_RADIUS_16_Data),
  sizeof(CS_FILTER_X_RADIUS_32_Data),
  sizeof(CS_FILTER_Y_RADIUS_32_Data),
};

#include "Shaders\inc\CS_BILATERAL_BLUR_RADIUS_16.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_RADIUS_15.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_RADIUS_14.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_RADIUS_13.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_RADIUS_12.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_RADIUS_11.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_RADIUS_10.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_RADIUS_9.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_RADIUS_8.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_RADIUS_7.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_RADIUS_6.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_RADIUS_5.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_RADIUS_4.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_RADIUS_3.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_RADIUS_2.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_RADIUS_1.inc"

const BYTE * CS_BILATERAL_BLUR_Data[] =
{
  //CS_BILATERAL_BLUR_RADIUS_1_DATA,
  CS_BILATERAL_BLUR_RADIUS_2_DATA,
  //CS_BILATERAL_BLUR_RADIUS_3_DATA,
  CS_BILATERAL_BLUR_RADIUS_4_DATA,
  //CS_BILATERAL_BLUR_RADIUS_5_DATA,
  //CS_BILATERAL_BLUR_RADIUS_6_DATA,
  //CS_BILATERAL_BLUR_RADIUS_7_DATA,
  CS_BILATERAL_BLUR_RADIUS_8_DATA,
  //CS_BILATERAL_BLUR_RADIUS_9_DATA,
  //CS_BILATERAL_BLUR_RADIUS_10_DATA,
  //CS_BILATERAL_BLUR_RADIUS_11_DATA,
  //CS_BILATERAL_BLUR_RADIUS_12_DATA,
  //CS_BILATERAL_BLUR_RADIUS_13_DATA,
  //CS_BILATERAL_BLUR_RADIUS_14_DATA,
  //CS_BILATERAL_BLUR_RADIUS_15_DATA,
  CS_BILATERAL_BLUR_RADIUS_16_DATA
};

int          CS_BILATERAL_BLUR_Size[] =
{

  //sizeof(CS_BILATERAL_BLUR_RADIUS_1_DATA),
  sizeof(CS_BILATERAL_BLUR_RADIUS_2_DATA),
  //sizeof(CS_BILATERAL_BLUR_RADIUS_3_DATA),
  sizeof(CS_BILATERAL_BLUR_RADIUS_4_DATA),
  //sizeof(CS_BILATERAL_BLUR_RADIUS_5_DATA),
  //sizeof(CS_BILATERAL_BLUR_RADIUS_6_DATA),
  //sizeof(CS_BILATERAL_BLUR_RADIUS_7_DATA),
  sizeof(CS_BILATERAL_BLUR_RADIUS_8_DATA),
  //sizeof(CS_BILATERAL_BLUR_RADIUS_9_DATA),
  //sizeof(CS_BILATERAL_BLUR_RADIUS_10_DATA),
  //sizeof(CS_BILATERAL_BLUR_RADIUS_11_DATA),
  //sizeof(CS_BILATERAL_BLUR_RADIUS_12_DATA),
  //sizeof(CS_BILATERAL_BLUR_RADIUS_13_DATA),
  //sizeof(CS_BILATERAL_BLUR_RADIUS_14_DATA),
  //sizeof(CS_BILATERAL_BLUR_RADIUS_15_DATA),
  sizeof(CS_BILATERAL_BLUR_RADIUS_16_DATA),
};

#include "Shaders\inc\CS_BILATERAL_BLUR_VERTICAL_RADIUS_16.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_VERTICAL_RADIUS_15.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_VERTICAL_RADIUS_14.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_VERTICAL_RADIUS_13.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_VERTICAL_RADIUS_12.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_VERTICAL_RADIUS_11.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_VERTICAL_RADIUS_10.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_VERTICAL_RADIUS_9.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_VERTICAL_RADIUS_8.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_VERTICAL_RADIUS_7.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_VERTICAL_RADIUS_6.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_VERTICAL_RADIUS_5.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_VERTICAL_RADIUS_4.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_VERTICAL_RADIUS_3.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_VERTICAL_RADIUS_2.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_VERTICAL_RADIUS_1.inc"

#include "Shaders\inc\CS_BILATERAL_BLUR_HORIZONTAL_RADIUS_16.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_HORIZONTAL_RADIUS_15.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_HORIZONTAL_RADIUS_14.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_HORIZONTAL_RADIUS_13.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_HORIZONTAL_RADIUS_12.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_HORIZONTAL_RADIUS_11.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_HORIZONTAL_RADIUS_10.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_HORIZONTAL_RADIUS_9.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_HORIZONTAL_RADIUS_8.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_HORIZONTAL_RADIUS_7.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_HORIZONTAL_RADIUS_6.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_HORIZONTAL_RADIUS_5.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_HORIZONTAL_RADIUS_4.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_HORIZONTAL_RADIUS_3.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_HORIZONTAL_RADIUS_2.inc"
#include "Shaders\inc\CS_BILATERAL_BLUR_HORIZONTAL_RADIUS_1.inc"

const BYTE * CS_BILATERAL_BLUR_SEPARABLE_Data[] =
{
  //CS_BILATERAL_BLUR_RADIUS_1_DATA,
  CS_BILATERAL_BLUR_HORIZONTAL_RADIUS_2_DATA,
  CS_BILATERAL_BLUR_VERTICAL_RADIUS_2_DATA,
  //CS_BILATERAL_BLUR_RADIUS_3_DATA,
  CS_BILATERAL_BLUR_HORIZONTAL_RADIUS_4_DATA,
  CS_BILATERAL_BLUR_VERTICAL_RADIUS_4_DATA,
  //CS_BILATERAL_BLUR_RADIUS_5_DATA,
  //CS_BILATERAL_BLUR_RADIUS_6_DATA,
  //CS_BILATERAL_BLUR_RADIUS_7_DATA,
  CS_BILATERAL_BLUR_HORIZONTAL_RADIUS_8_DATA,
  CS_BILATERAL_BLUR_VERTICAL_RADIUS_8_DATA,
  //CS_BILATERAL_BLUR_RADIUS_9_DATA,
  //CS_BILATERAL_BLUR_RADIUS_10_DATA,
  //CS_BILATERAL_BLUR_RADIUS_11_DATA,
  //CS_BILATERAL_BLUR_RADIUS_12_DATA,
  //CS_BILATERAL_BLUR_RADIUS_13_DATA,
  //CS_BILATERAL_BLUR_RADIUS_14_DATA,
  //CS_BILATERAL_BLUR_RADIUS_15_DATA,
  CS_BILATERAL_BLUR_HORIZONTAL_RADIUS_16_DATA,
  CS_BILATERAL_BLUR_VERTICAL_RADIUS_16_DATA,
};

int          CS_BILATERAL_BLUR_SEPARABLE_Size[] =
{

  //sizeof(CS_BILATERAL_BLUR_RADIUS_1_DATA),
  sizeof(CS_BILATERAL_BLUR_HORIZONTAL_RADIUS_2_DATA),
  sizeof(CS_BILATERAL_BLUR_VERTICAL_RADIUS_2_DATA),
  //sizeof(CS_BILATERAL_BLUR_RADIUS_3_DATA),
  sizeof(CS_BILATERAL_BLUR_HORIZONTAL_RADIUS_4_DATA),
  sizeof(CS_BILATERAL_BLUR_VERTICAL_RADIUS_4_DATA),
  //sizeof(CS_BILATERAL_BLUR_RADIUS_5_DATA),
  //sizeof(CS_BILATERAL_BLUR_RADIUS_6_DATA),
  //sizeof(CS_BILATERAL_BLUR_RADIUS_7_DATA),
  sizeof(CS_BILATERAL_BLUR_HORIZONTAL_RADIUS_8_DATA),
  sizeof(CS_BILATERAL_BLUR_VERTICAL_RADIUS_8_DATA),
  //sizeof(CS_BILATERAL_BLUR_RADIUS_9_DATA),
  //sizeof(CS_BILATERAL_BLUR_RADIUS_10_DATA),
  //sizeof(CS_BILATERAL_BLUR_RADIUS_11_DATA),
  //sizeof(CS_BILATERAL_BLUR_RADIUS_12_DATA),
  //sizeof(CS_BILATERAL_BLUR_RADIUS_13_DATA),
  //sizeof(CS_BILATERAL_BLUR_RADIUS_14_DATA),
  //sizeof(CS_BILATERAL_BLUR_RADIUS_15_DATA),
  sizeof(CS_BILATERAL_BLUR_HORIZONTAL_RADIUS_16_DATA),
  sizeof(CS_BILATERAL_BLUR_VERTICAL_RADIUS_16_DATA),
};


#include "Shaders\inc\CS_AO_LOW_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\CS_AO_LOW_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\CS_AO_LOW_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\CS_AO_LOW_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\CS_AO_LOW_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\CS_AO_LOW_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\CS_AO_MEDIUM_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\CS_AO_MEDIUM_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\CS_AO_MEDIUM_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\CS_AO_MEDIUM_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\CS_AO_MEDIUM_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\CS_AO_MEDIUM_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\CS_AO_HIGH_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\CS_AO_HIGH_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\CS_AO_HIGH_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\CS_AO_HIGH_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\CS_AO_HIGH_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\CS_AO_HIGH_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\CS_AO_ULTRA_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\CS_AO_ULTRA_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\CS_AO_ULTRA_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\CS_AO_ULTRA_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\CS_AO_ULTRA_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\CS_AO_ULTRA_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_SRV.inc"

#include "Shaders\inc\CS_AO_DEIN_X2_LOW_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\CS_AO_DEIN_X2_LOW_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\CS_AO_DEIN_X2_LOW_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\CS_AO_DEIN_X2_LOW_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\CS_AO_DEIN_X2_LOW_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\CS_AO_DEIN_X2_LOW_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\CS_AO_DEIN_X2_MEDIUM_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\CS_AO_DEIN_X2_MEDIUM_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\CS_AO_DEIN_X2_MEDIUM_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\CS_AO_DEIN_X2_MEDIUM_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\CS_AO_DEIN_X2_MEDIUM_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\CS_AO_DEIN_X2_MEDIUM_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\CS_AO_DEIN_X2_HIGH_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\CS_AO_DEIN_X2_HIGH_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\CS_AO_DEIN_X2_HIGH_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\CS_AO_DEIN_X2_HIGH_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\CS_AO_DEIN_X2_HIGH_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\CS_AO_DEIN_X2_HIGH_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\CS_AO_DEIN_X2_ULTRA_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\CS_AO_DEIN_X2_ULTRA_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\CS_AO_DEIN_X2_ULTRA_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\CS_AO_DEIN_X2_ULTRA_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\CS_AO_DEIN_X2_ULTRA_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\CS_AO_DEIN_X2_ULTRA_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_SRV.inc"

#include "Shaders\inc\CS_AO_DEIN_X4_LOW_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\CS_AO_DEIN_X4_LOW_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\CS_AO_DEIN_X4_LOW_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\CS_AO_DEIN_X4_LOW_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\CS_AO_DEIN_X4_LOW_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\CS_AO_DEIN_X4_LOW_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\CS_AO_DEIN_X4_MEDIUM_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\CS_AO_DEIN_X4_MEDIUM_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\CS_AO_DEIN_X4_MEDIUM_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\CS_AO_DEIN_X4_MEDIUM_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\CS_AO_DEIN_X4_MEDIUM_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\CS_AO_DEIN_X4_MEDIUM_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\CS_AO_DEIN_X4_HIGH_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\CS_AO_DEIN_X4_HIGH_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\CS_AO_DEIN_X4_HIGH_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\CS_AO_DEIN_X4_HIGH_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\CS_AO_DEIN_X4_HIGH_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\CS_AO_DEIN_X4_HIGH_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\CS_AO_DEIN_X4_ULTRA_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\CS_AO_DEIN_X4_ULTRA_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\CS_AO_DEIN_X4_ULTRA_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\CS_AO_DEIN_X4_ULTRA_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\CS_AO_DEIN_X4_ULTRA_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\CS_AO_DEIN_X4_ULTRA_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_SRV.inc"

#include "Shaders\inc\CS_AO_DEIN_X8_LOW_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\CS_AO_DEIN_X8_LOW_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\CS_AO_DEIN_X8_LOW_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\CS_AO_DEIN_X8_LOW_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\CS_AO_DEIN_X8_LOW_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\CS_AO_DEIN_X8_LOW_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\CS_AO_DEIN_X8_MEDIUM_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\CS_AO_DEIN_X8_MEDIUM_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\CS_AO_DEIN_X8_MEDIUM_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\CS_AO_DEIN_X8_MEDIUM_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\CS_AO_DEIN_X8_MEDIUM_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\CS_AO_DEIN_X8_MEDIUM_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\CS_AO_DEIN_X8_HIGH_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\CS_AO_DEIN_X8_HIGH_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\CS_AO_DEIN_X8_HIGH_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\CS_AO_DEIN_X8_HIGH_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\CS_AO_DEIN_X8_HIGH_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\CS_AO_DEIN_X8_HIGH_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\CS_AO_DEIN_X8_ULTRA_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\CS_AO_DEIN_X8_ULTRA_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\CS_AO_DEIN_X8_ULTRA_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\CS_AO_DEIN_X8_ULTRA_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\CS_AO_DEIN_X8_ULTRA_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\CS_AO_DEIN_X8_ULTRA_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_SRV.inc"

const BYTE * CS_AMD_AO_Data[] =
{
  // Layer // Normal // Tap // Sample
  CS_AO_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_08_Data,
  CS_AO_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_16_Data,
  CS_AO_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_24_Data,
  CS_AO_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_32_Data,

  CS_AO_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_08_Data,
  CS_AO_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_16_Data,
  CS_AO_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_24_Data,
  CS_AO_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_32_Data,

  CS_AO_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_08_Data,
  CS_AO_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_16_Data,
  CS_AO_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_24_Data,
  CS_AO_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_32_Data,

  CS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_08_Data,
  CS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_16_Data,
  CS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_24_Data,
  CS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_32_Data,

  CS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_08_Data,
  CS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_16_Data,
  CS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_24_Data,
  CS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_32_Data,

  CS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_08_Data,
  CS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_16_Data,
  CS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_24_Data,
  CS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_32_Data,

  CS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_08_Data,
  CS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_16_Data,
  CS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_24_Data,
  CS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_32_Data,

  CS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_08_Data,
  CS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_16_Data,
  CS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_24_Data,
  CS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_32_Data,

  CS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_08_Data,
  CS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_16_Data,
  CS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_24_Data,
  CS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_32_Data,

  CS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_08_Data,
  CS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_16_Data,
  CS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_24_Data,
  CS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_32_Data,

  CS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_08_Data,
  CS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_16_Data,
  CS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_24_Data,
  CS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_32_Data,

  CS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_08_Data,
  CS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_16_Data,
  CS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_24_Data,
  CS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_32_Data,

  CS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_08_Data,
  CS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_16_Data,
  CS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_24_Data,
  CS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_32_Data,

  CS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_08_Data,
  CS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_16_Data,
  CS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_24_Data,
  CS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_32_Data,

  CS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_08_Data,
  CS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_16_Data,
  CS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_24_Data,
  CS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_32_Data,

  CS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_08_Data,
  CS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_16_Data,
  CS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_24_Data,
  CS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_32_Data,

  CS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_08_Data,
  CS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_16_Data,
  CS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_24_Data,
  CS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_32_Data,

  CS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_08_Data,
  CS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_16_Data,
  CS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_24_Data,
  CS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_32_Data,

  CS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_08_Data,
  CS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_16_Data,
  CS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_24_Data,
  CS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_32_Data,

  CS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_08_Data,
  CS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_16_Data,
  CS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_24_Data,
  CS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_32_Data,

  CS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_08_Data,
  CS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_16_Data,
  CS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_24_Data,
  CS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_32_Data,

  CS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_08_Data,
  CS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_16_Data,
  CS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_24_Data,
  CS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_32_Data,

  CS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_08_Data,
  CS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_16_Data,
  CS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_24_Data,
  CS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_32_Data,

  CS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_08_Data,
  CS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_16_Data,
  CS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_24_Data,
  CS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_32_Data,
};

int          CS_AMD_AO_Size[] =
{
  sizeof(CS_AO_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_08_Data),
  sizeof(CS_AO_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_16_Data),
  sizeof(CS_AO_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_24_Data),
  sizeof(CS_AO_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_32_Data),

  sizeof(CS_AO_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_08_Data),
  sizeof(CS_AO_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_16_Data),
  sizeof(CS_AO_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_24_Data),
  sizeof(CS_AO_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_32_Data),

  sizeof(CS_AO_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_08_Data),
  sizeof(CS_AO_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_16_Data),
  sizeof(CS_AO_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_24_Data),
  sizeof(CS_AO_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_32_Data),

  sizeof(CS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_08_Data),
  sizeof(CS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_16_Data),
  sizeof(CS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_24_Data),
  sizeof(CS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_32_Data),

  sizeof(CS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_08_Data),
  sizeof(CS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_16_Data),
  sizeof(CS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_24_Data),
  sizeof(CS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_32_Data),

  sizeof(CS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_08_Data),
  sizeof(CS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_16_Data),
  sizeof(CS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_24_Data),
  sizeof(CS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_32_Data),

  sizeof(CS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_08_Data),
  sizeof(CS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_16_Data),
  sizeof(CS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_24_Data),
  sizeof(CS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_32_Data),

  sizeof(CS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_08_Data),
  sizeof(CS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_16_Data),
  sizeof(CS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_24_Data),
  sizeof(CS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_32_Data),

  sizeof(CS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_08_Data),
  sizeof(CS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_16_Data),
  sizeof(CS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_24_Data),
  sizeof(CS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_32_Data),

  sizeof(CS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_08_Data),
  sizeof(CS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_16_Data),
  sizeof(CS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_24_Data),
  sizeof(CS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_32_Data),

  sizeof(CS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_08_Data),
  sizeof(CS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_16_Data),
  sizeof(CS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_24_Data),
  sizeof(CS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_32_Data),

  sizeof(CS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_08_Data),
  sizeof(CS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_16_Data),
  sizeof(CS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_24_Data),
  sizeof(CS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_32_Data),

  sizeof(CS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_08_Data),
  sizeof(CS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_16_Data),
  sizeof(CS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_24_Data),
  sizeof(CS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_32_Data),

  sizeof(CS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_08_Data),
  sizeof(CS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_16_Data),
  sizeof(CS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_24_Data),
  sizeof(CS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_32_Data),

  sizeof(CS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_08_Data),
  sizeof(CS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_16_Data),
  sizeof(CS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_24_Data),
  sizeof(CS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_32_Data),

  sizeof(CS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_08_Data),
  sizeof(CS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_16_Data),
  sizeof(CS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_24_Data),
  sizeof(CS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_32_Data),

  sizeof(CS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_08_Data),
  sizeof(CS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_16_Data),
  sizeof(CS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_24_Data),
  sizeof(CS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_32_Data),

  sizeof(CS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_08_Data),
  sizeof(CS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_16_Data),
  sizeof(CS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_24_Data),
  sizeof(CS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_32_Data),

  sizeof(CS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_08_Data),
  sizeof(CS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_16_Data),
  sizeof(CS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_24_Data),
  sizeof(CS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_32_Data),

  sizeof(CS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_08_Data),
  sizeof(CS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_16_Data),
  sizeof(CS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_24_Data),
  sizeof(CS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_32_Data),

  sizeof(CS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_08_Data),
  sizeof(CS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_16_Data),
  sizeof(CS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_24_Data),
  sizeof(CS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_32_Data),

  sizeof(CS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_08_Data),
  sizeof(CS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_16_Data),
  sizeof(CS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_24_Data),
  sizeof(CS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_32_Data),

  sizeof(CS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_08_Data),
  sizeof(CS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_16_Data),
  sizeof(CS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_24_Data),
  sizeof(CS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_32_Data),

  sizeof(CS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_08_Data),
  sizeof(CS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_16_Data),
  sizeof(CS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_24_Data),
  sizeof(CS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_32_Data),
};

#include "Shaders\inc\PS_AO_LOW_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\PS_AO_LOW_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\PS_AO_LOW_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\PS_AO_LOW_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\PS_AO_LOW_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\PS_AO_LOW_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\PS_AO_MEDIUM_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\PS_AO_MEDIUM_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\PS_AO_MEDIUM_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\PS_AO_MEDIUM_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\PS_AO_MEDIUM_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\PS_AO_MEDIUM_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\PS_AO_HIGH_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\PS_AO_HIGH_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\PS_AO_HIGH_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\PS_AO_HIGH_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\PS_AO_HIGH_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\PS_AO_HIGH_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\PS_AO_ULTRA_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\PS_AO_ULTRA_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\PS_AO_ULTRA_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\PS_AO_ULTRA_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\PS_AO_ULTRA_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\PS_AO_ULTRA_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_SRV.inc"

#include "Shaders\inc\PS_AO_DEIN_X2_LOW_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\PS_AO_DEIN_X2_LOW_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\PS_AO_DEIN_X2_LOW_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\PS_AO_DEIN_X2_LOW_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\PS_AO_DEIN_X2_LOW_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\PS_AO_DEIN_X2_LOW_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\PS_AO_DEIN_X2_MEDIUM_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\PS_AO_DEIN_X2_MEDIUM_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\PS_AO_DEIN_X2_MEDIUM_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\PS_AO_DEIN_X2_MEDIUM_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\PS_AO_DEIN_X2_MEDIUM_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\PS_AO_DEIN_X2_MEDIUM_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\PS_AO_DEIN_X2_HIGH_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\PS_AO_DEIN_X2_HIGH_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\PS_AO_DEIN_X2_HIGH_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\PS_AO_DEIN_X2_HIGH_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\PS_AO_DEIN_X2_HIGH_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\PS_AO_DEIN_X2_HIGH_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\PS_AO_DEIN_X2_ULTRA_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\PS_AO_DEIN_X2_ULTRA_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\PS_AO_DEIN_X2_ULTRA_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\PS_AO_DEIN_X2_ULTRA_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\PS_AO_DEIN_X2_ULTRA_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\PS_AO_DEIN_X2_ULTRA_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_SRV.inc"

#include "Shaders\inc\PS_AO_DEIN_X4_LOW_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\PS_AO_DEIN_X4_LOW_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\PS_AO_DEIN_X4_LOW_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\PS_AO_DEIN_X4_LOW_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\PS_AO_DEIN_X4_LOW_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\PS_AO_DEIN_X4_LOW_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\PS_AO_DEIN_X4_MEDIUM_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\PS_AO_DEIN_X4_MEDIUM_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\PS_AO_DEIN_X4_MEDIUM_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\PS_AO_DEIN_X4_MEDIUM_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\PS_AO_DEIN_X4_MEDIUM_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\PS_AO_DEIN_X4_MEDIUM_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\PS_AO_DEIN_X4_HIGH_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\PS_AO_DEIN_X4_HIGH_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\PS_AO_DEIN_X4_HIGH_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\PS_AO_DEIN_X4_HIGH_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\PS_AO_DEIN_X4_HIGH_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\PS_AO_DEIN_X4_HIGH_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\PS_AO_DEIN_X4_ULTRA_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\PS_AO_DEIN_X4_ULTRA_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\PS_AO_DEIN_X4_ULTRA_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\PS_AO_DEIN_X4_ULTRA_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\PS_AO_DEIN_X4_ULTRA_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\PS_AO_DEIN_X4_ULTRA_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_SRV.inc"

#include "Shaders\inc\PS_AO_DEIN_X8_LOW_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\PS_AO_DEIN_X8_LOW_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\PS_AO_DEIN_X8_LOW_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\PS_AO_DEIN_X8_LOW_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\PS_AO_DEIN_X8_LOW_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\PS_AO_DEIN_X8_LOW_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\PS_AO_DEIN_X8_MEDIUM_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\PS_AO_DEIN_X8_MEDIUM_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\PS_AO_DEIN_X8_MEDIUM_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\PS_AO_DEIN_X8_MEDIUM_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\PS_AO_DEIN_X8_MEDIUM_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\PS_AO_DEIN_X8_MEDIUM_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\PS_AO_DEIN_X8_HIGH_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\PS_AO_DEIN_X8_HIGH_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\PS_AO_DEIN_X8_HIGH_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\PS_AO_DEIN_X8_HIGH_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\PS_AO_DEIN_X8_HIGH_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\PS_AO_DEIN_X8_HIGH_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\PS_AO_DEIN_X8_ULTRA_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\PS_AO_DEIN_X8_ULTRA_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\PS_AO_DEIN_X8_ULTRA_SAMPLES_NORMAL_OPTION_NONE_TAP_TYPE_RANDOM_SRV.inc"
#include "Shaders\inc\PS_AO_DEIN_X8_ULTRA_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_FIXED.inc"
#include "Shaders\inc\PS_AO_DEIN_X8_ULTRA_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_CB.inc"
#include "Shaders\inc\PS_AO_DEIN_X8_ULTRA_SAMPLES_NORMAL_OPTION_READ_FROM_SRV_TAP_TYPE_RANDOM_SRV.inc"

const BYTE * PS_AMD_AO_Data[] =
{
  PS_AO_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_08_Data,
  PS_AO_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_16_Data,
  PS_AO_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_24_Data,
  PS_AO_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_32_Data,

  PS_AO_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_08_Data,
  PS_AO_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_16_Data,
  PS_AO_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_24_Data,
  PS_AO_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_32_Data,

  PS_AO_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_08_Data,
  PS_AO_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_16_Data,
  PS_AO_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_24_Data,
  PS_AO_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_32_Data,

  PS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_08_Data,
  PS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_16_Data,
  PS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_24_Data,
  PS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_32_Data,

  PS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_08_Data,
  PS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_16_Data,
  PS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_24_Data,
  PS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_32_Data,

  PS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_08_Data,
  PS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_16_Data,
  PS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_24_Data,
  PS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_32_Data,

  PS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_08_Data,
  PS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_16_Data,
  PS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_24_Data,
  PS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_32_Data,

  PS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_08_Data,
  PS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_16_Data,
  PS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_24_Data,
  PS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_32_Data,

  PS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_08_Data,
  PS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_16_Data,
  PS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_24_Data,
  PS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_32_Data,

  PS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_08_Data,
  PS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_16_Data,
  PS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_24_Data,
  PS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_32_Data,

  PS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_08_Data,
  PS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_16_Data,
  PS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_24_Data,
  PS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_32_Data,

  PS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_08_Data,
  PS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_16_Data,
  PS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_24_Data,
  PS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_32_Data,

  PS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_08_Data,
  PS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_16_Data,
  PS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_24_Data,
  PS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_32_Data,

  PS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_08_Data,
  PS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_16_Data,
  PS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_24_Data,
  PS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_32_Data,

  PS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_08_Data,
  PS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_16_Data,
  PS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_24_Data,
  PS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_32_Data,

  PS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_08_Data,
  PS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_16_Data,
  PS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_24_Data,
  PS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_32_Data,

  PS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_08_Data,
  PS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_16_Data,
  PS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_24_Data,
  PS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_32_Data,

  PS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_08_Data,
  PS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_16_Data,
  PS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_24_Data,
  PS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_32_Data,

  PS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_08_Data,
  PS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_16_Data,
  PS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_24_Data,
  PS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_32_Data,

  PS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_08_Data,
  PS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_16_Data,
  PS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_24_Data,
  PS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_32_Data,

  PS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_08_Data,
  PS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_16_Data,
  PS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_24_Data,
  PS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_32_Data,

  PS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_08_Data,
  PS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_16_Data,
  PS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_24_Data,
  PS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_32_Data,

  PS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_08_Data,
  PS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_16_Data,
  PS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_24_Data,
  PS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_32_Data,

  PS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_08_Data,
  PS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_16_Data,
  PS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_24_Data,
  PS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_32_Data,

};

int          PS_AMD_AO_Size[] =
{
  sizeof(PS_AO_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_08_Data),
  sizeof(PS_AO_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_16_Data),
  sizeof(PS_AO_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_24_Data),
  sizeof(PS_AO_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_32_Data),

  sizeof(PS_AO_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_08_Data),
  sizeof(PS_AO_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_16_Data),
  sizeof(PS_AO_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_24_Data),
  sizeof(PS_AO_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_32_Data),

  sizeof(PS_AO_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_08_Data),
  sizeof(PS_AO_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_16_Data),
  sizeof(PS_AO_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_24_Data),
  sizeof(PS_AO_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_32_Data),

  sizeof(PS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_08_Data),
  sizeof(PS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_16_Data),
  sizeof(PS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_24_Data),
  sizeof(PS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_32_Data),

  sizeof(PS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_08_Data),
  sizeof(PS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_16_Data),
  sizeof(PS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_24_Data),
  sizeof(PS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_32_Data),

  sizeof(PS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_08_Data),
  sizeof(PS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_16_Data),
  sizeof(PS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_24_Data),
  sizeof(PS_AO_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_32_Data),

  sizeof(PS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_08_Data),
  sizeof(PS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_16_Data),
  sizeof(PS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_24_Data),
  sizeof(PS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_32_Data),

  sizeof(PS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_08_Data),
  sizeof(PS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_16_Data),
  sizeof(PS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_24_Data),
  sizeof(PS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_32_Data),

  sizeof(PS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_08_Data),
  sizeof(PS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_16_Data),
  sizeof(PS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_24_Data),
  sizeof(PS_AO_DEIN_X2_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_32_Data),

  sizeof(PS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_08_Data),
  sizeof(PS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_16_Data),
  sizeof(PS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_24_Data),
  sizeof(PS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_32_Data),

  sizeof(PS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_08_Data),
  sizeof(PS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_16_Data),
  sizeof(PS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_24_Data),
  sizeof(PS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_32_Data),

  sizeof(PS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_08_Data),
  sizeof(PS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_16_Data),
  sizeof(PS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_24_Data),
  sizeof(PS_AO_DEIN_X2_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_32_Data),

  sizeof(PS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_08_Data),
  sizeof(PS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_16_Data),
  sizeof(PS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_24_Data),
  sizeof(PS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_32_Data),

  sizeof(PS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_08_Data),
  sizeof(PS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_16_Data),
  sizeof(PS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_24_Data),
  sizeof(PS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_32_Data),

  sizeof(PS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_08_Data),
  sizeof(PS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_16_Data),
  sizeof(PS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_24_Data),
  sizeof(PS_AO_DEIN_X4_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_32_Data),

  sizeof(PS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_08_Data),
  sizeof(PS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_16_Data),
  sizeof(PS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_24_Data),
  sizeof(PS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_32_Data),

  sizeof(PS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_08_Data),
  sizeof(PS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_16_Data),
  sizeof(PS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_24_Data),
  sizeof(PS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_32_Data),

  sizeof(PS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_08_Data),
  sizeof(PS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_16_Data),
  sizeof(PS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_24_Data),
  sizeof(PS_AO_DEIN_X4_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_32_Data),

  sizeof(PS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_08_Data),
  sizeof(PS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_16_Data),
  sizeof(PS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_24_Data),
  sizeof(PS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_FIXED_SAMPLES_32_Data),

  sizeof(PS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_08_Data),
  sizeof(PS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_16_Data),
  sizeof(PS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_24_Data),
  sizeof(PS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_RANDOM_CB_SAMPLES_32_Data),

  sizeof(PS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_08_Data),
  sizeof(PS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_16_Data),
  sizeof(PS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_24_Data),
  sizeof(PS_AO_DEIN_X8_NORMAL_OPTION_NONE_TAP_RANDOM_SRV_SAMPLES_32_Data),

  sizeof(PS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_08_Data),
  sizeof(PS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_16_Data),
  sizeof(PS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_24_Data),
  sizeof(PS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_FIXED_SAMPLES_32_Data),

  sizeof(PS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_08_Data),
  sizeof(PS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_16_Data),
  sizeof(PS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_24_Data),
  sizeof(PS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_CB_SAMPLES_32_Data),

  sizeof(PS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_08_Data),
  sizeof(PS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_16_Data),
  sizeof(PS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_24_Data),
  sizeof(PS_AO_DEIN_X8_NORMAL_OPTION_READ_FROM_SRV_TAP_RANDOM_SRV_SAMPLES_32_Data),
};